"""
Text PII screening — two-pass pipeline:
  Pass 1: Presidio (fast, pattern-based, local)
  Pass 2: Ollama/Ministral (contextual gaps, local)
Replacements are coherent fakes generated by Ollama.
Nothing leaves the machine during this stage.
"""
import json
import re
from typing import Dict, List, Tuple

import ollama
from presidio_analyzer import AnalyzerEngine, Pattern, PatternRecognizer
from presidio_anonymizer import AnonymizerEngine

from app.config import settings
from app.screening.entity_settings import get as get_entities
from app.vault.store import vault

# ── Presidio setup ────────────────────────────────────────────────────────────
analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()

# Presidio's built-in CREDIT_CARD recognizer requires a valid Luhn checksum,
# which rejects test/fake card numbers. This relaxed pattern catches any
# 16-digit group (4×4 separated by spaces or dashes) regardless of Luhn.
_cc_relaxed = PatternRecognizer(
    supported_entity="CREDIT_CARD",
    patterns=[
        Pattern(
            name="credit_card_relaxed",
            regex=r"\b\d{4}[\s\-]\d{4}[\s\-]\d{4}[\s\-]\d{4}\b",
            score=0.5,
        )
    ],
)
analyzer.registry.add_recognizer(_cc_relaxed)

# Human-readable labels sent to Ollama — must match what Ollama will echo back as "type"
_ENTITY_LABELS: Dict[str, str] = {
    "PERSON":          "person name",
    "EMAIL_ADDRESS":   "email address",
    "PHONE_NUMBER":    "phone number",
    "LOCATION":        "location or address",
    "CREDIT_CARD":     "credit card number",
    "IBAN_CODE":       "IBAN or bank account number",
    "IP_ADDRESS":      "IP address",
    "US_SSN":          "US Social Security Number",
    "US_PASSPORT":     "US passport number",
    "DATE_TIME":       "date or time",
    "NRP":             "nationality, religion, or political affiliation",
    "URL":             "URL or website",
    "MEDICAL_LICENSE": "medical license number",
    "ORGANIZATION":    "organization or company name",
}


def _matches_active(ollama_type: str, active_entities: List[str]) -> bool:
    """Return True if the Ollama-reported type corresponds to any active Presidio entity."""
    t = ollama_type.lower().strip()
    for entity in active_entities:
        label = _ENTITY_LABELS.get(entity, entity.lower().replace("_", " ")).lower()
        if t == label or t == entity.lower() or t == entity.lower().replace("_", " "):
            return True
        # Partial word overlap handles abbreviations ("address" → "location or address")
        label_words = {w for w in label.replace("/", " ").replace(",", " ").split() if len(w) > 3}
        type_words  = {w for w in t.replace("/", " ").replace(",", " ").split()  if len(w) > 3}
        if label_words & type_words:
            return True
    return False


PRESIDIO_ENTITIES = [
    "PERSON",
    "EMAIL_ADDRESS",
    "PHONE_NUMBER",
    "LOCATION",
    "ORGANIZATION",
    "CREDIT_CARD",
    "IBAN_CODE",
    "IP_ADDRESS",
    "US_SSN",
    "US_PASSPORT",
    "DATE_TIME",
    "NRP",
    "URL",
    "MEDICAL_LICENSE",
]

# Module-level fake cache so the same real value always gets the same fake
_fake_cache: Dict[str, str] = {}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _presidio_hits(text: str, entities: List[str] | None = None) -> List[Dict]:
    """Return Presidio findings as a list of dicts with span info."""
    active = entities if entities is not None else get_entities("text")
    if not active:
        return []
    results = analyzer.analyze(text=text, entities=active, language="en")
    return [
        {
            "entity_type": r.entity_type,
            "start": r.start,
            "end": r.end,
            "score": round(r.score, 3),
            "value": text[r.start : r.end],
        }
        for r in results
    ]


async def _ollama_hits(text: str, active_entities: List[str]) -> List[Dict]:
    """Ask local Ollama to spot contextual PII that patterns miss, restricted to active entity types."""
    if not active_entities:
        return []
    labels = [_ENTITY_LABELS.get(e, e.lower().replace("_", " ")) for e in active_entities]
    entity_list = ", ".join(f'"{lbl}"' for lbl in labels)
    prompt = (
        "Find personally identifiable information (PII) in the text below that a regex engine might miss.\n"
        f"Only look for these types: {entity_list}.\n"
        "PII is data that identifies or could identify a real specific person.\n"
        "Do NOT flag: commands, instructions, questions, intents, topics, generic words, "
        "adjectives, or anything that is not directly tied to a specific individual's identity.\n"
        "Return ONLY a compact JSON array. Each item: "
        '{"value": "<exact substring from text>", "type": "<one of the listed types>"}. '
        "If nothing found return [].\n\n"
        f"TEXT:\n{text}\n\nJSON:"
    )
    try:
        resp = ollama.generate(
            model=settings.ollama_model,
            prompt=prompt,
            options={"temperature": 0.1},
        )
        raw = resp["response"].strip()
        m = re.search(r"\[.*?\]", raw, re.DOTALL)
        if m:
            hits = json.loads(m.group())
            return [h for h in hits if _matches_active(h.get("type", ""), active_entities)]
    except Exception:
        pass
    return []


async def _make_fake(entity_type: str, original: str) -> str:
    """Generate a coherent fake replacement (cached per real value)."""
    if original in _fake_cache:
        return _fake_cache[original]

    max_words = max(len(original.split()), 4)
    prompt = (
        f'Replace this {entity_type} with a realistic fake: "{original}". '
        f"Output ONLY the replacement — no explanation, no punctuation around it, no extra words. "
        f"Maximum {max_words} words."
    )
    try:
        resp = ollama.generate(
            model=settings.ollama_model,
            prompt=prompt,
            options={"temperature": 0.8, "num_predict": 20},
        )
        # Take first non-empty line only — discard any explanation the model adds
        fake = next(
            (line.strip().strip("\"'") for line in resp["response"].splitlines() if line.strip()),
            "",
        )
        # Hard cap: never longer than 2× the original
        if len(fake) > len(original) * 2:
            fake = fake[:len(original) * 2].rsplit(" ", 1)[0]
        fake = fake or f"[REDACTED_{entity_type}]"
    except Exception:
        fake = f"[REDACTED_{entity_type}]"

    _fake_cache[original] = fake
    return fake


# ── Public API ────────────────────────────────────────────────────────────────

async def screen_text(text: str, session_id: str, entities: List[str] | None = None) -> Tuple[str, List[Dict]]:
    """
    Screen *text* for PII.  Returns (redacted_text, findings).

    Uses Presidio spans for precise replacement (end→start order so offsets
    stay valid), then Ollama for any contextual PII still in the redacted copy.
    All fakes stored in the session vault.
    """
    if not text or not text.strip():
        return text, []

    active_entities = entities if entities is not None else get_entities("text")
    if not active_entities:
        return text, []

    findings: List[Dict] = []
    already_replaced: set = set()

    # ── Pass 1: Presidio (span-based, most accurate) ─────────────────────────
    hits = _presidio_hits(text, entities=entities)
    chars = list(text)

    for hit in sorted(hits, key=lambda h: h["start"], reverse=True):
        original = hit["value"]

        # Reuse existing fake for this session if we already vaulted it
        fake = vault.fake_for(session_id, original) or await _make_fake(
            hit["entity_type"], original
        )
        vault.put(session_id, fake, original)
        chars[hit["start"] : hit["end"]] = list(fake)
        already_replaced.add(original)
        findings.append({**hit, "fake": fake, "source": "presidio"})

    redacted = "".join(chars)

    # Sweep for any remaining occurrences Presidio's NER missed (e.g. name in quotes)
    for original in list(already_replaced):
        fake = vault.fake_for(session_id, original)
        if fake and original in redacted:
            redacted = redacted.replace(original, fake)

    # ── Pass 2: Ollama contextual ─────────────────────────────────────────────
    ollama_hits = await _ollama_hits(text, active_entities)  # screen original to get clean spans

    for hit in ollama_hits:
        original = hit.get("value", "")
        if not original or original in already_replaced:
            continue
        if original not in redacted:
            continue

        fake = vault.fake_for(session_id, original) or await _make_fake(
            hit.get("type", "PII"), original
        )
        vault.put(session_id, fake, original)
        redacted = redacted.replace(original, fake)
        already_replaced.add(original)
        findings.append(
            {
                "entity_type": hit.get("type", "PII"),
                "value": original,
                "fake": fake,
                "source": "ollama",
                "score": 0.7,
            }
        )

    return redacted, findings
