"""
Text PII screening — two-pass pipeline:
  Pass 1: Presidio (fast, pattern-based, local)
  Pass 2: Ollama/Ministral (contextual gaps, local)
Replacements are coherent fakes generated by Ollama.
Nothing leaves the machine during this stage.
"""
import json
import re
from typing import Dict, List, Tuple

import ollama
from presidio_analyzer import AnalyzerEngine, Pattern, PatternRecognizer
from presidio_anonymizer import AnonymizerEngine

from app.config import settings
from app.vault.store import vault

# ── Presidio setup ────────────────────────────────────────────────────────────
analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()

# Presidio's built-in CREDIT_CARD recognizer requires a valid Luhn checksum,
# which rejects test/fake card numbers. This relaxed pattern catches any
# 16-digit group (4×4 separated by spaces or dashes) regardless of Luhn.
_cc_relaxed = PatternRecognizer(
    supported_entity="CREDIT_CARD",
    patterns=[
        Pattern(
            name="credit_card_relaxed",
            regex=r"\b\d{4}[\s\-]\d{4}[\s\-]\d{4}[\s\-]\d{4}\b",
            score=0.5,
        )
    ],
)
analyzer.registry.add_recognizer(_cc_relaxed)

PRESIDIO_ENTITIES = [
    "PERSON",
    "EMAIL_ADDRESS",
    "PHONE_NUMBER",
    "LOCATION",
    "ORGANIZATION",
    "CREDIT_CARD",
    "IBAN_CODE",
    "IP_ADDRESS",
    "US_SSN",
    "US_PASSPORT",
    "DATE_TIME",
    "NRP",
    "URL",
    "MEDICAL_LICENSE",
]

# Module-level fake cache so the same real value always gets the same fake
_fake_cache: Dict[str, str] = {}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _presidio_hits(text: str) -> List[Dict]:
    """Return Presidio findings as a list of dicts with span info."""
    results = analyzer.analyze(text=text, entities=PRESIDIO_ENTITIES, language="en")
    return [
        {
            "entity_type": r.entity_type,
            "start": r.start,
            "end": r.end,
            "score": round(r.score, 3),
            "value": text[r.start : r.end],
        }
        for r in results
    ]


async def _ollama_hits(text: str) -> List[Dict]:
    """Ask local Ollama to spot contextual PII that patterns miss."""
    prompt = (
        "Find any personally identifiable information (PII) in the text below "
        "that a regex engine might miss — names used informally, implied locations, "
        "account references, credentials, etc.\n"
        "Return ONLY a compact JSON array. Each item: "
        '{"value": "<exact substring>", "type": "<PII type>"}. '
        "If nothing found return [].\n\n"
        f"TEXT:\n{text}\n\nJSON:"
    )
    try:
        resp = ollama.generate(
            model=settings.ollama_model,
            prompt=prompt,
            options={"temperature": 0.1},
        )
        raw = resp["response"].strip()
        m = re.search(r"\[.*?\]", raw, re.DOTALL)
        if m:
            return json.loads(m.group())
    except Exception:
        pass
    return []


async def _make_fake(entity_type: str, original: str) -> str:
    """Generate a coherent fake replacement (cached per real value)."""
    if original in _fake_cache:
        return _fake_cache[original]

    prompt = (
        f'Generate a realistic fake replacement for this {entity_type}: "{original}". '
        "Output the replacement value only — one line, no explanation, no quotes, no extra words."
    )
    try:
        resp = ollama.generate(
            model=settings.ollama_model,
            prompt=prompt,
            options={"temperature": 0.8},
        )
        # Take first non-empty line only — discard any explanation the model adds
        fake = next(
            (line.strip().strip("\"'") for line in resp["response"].splitlines() if line.strip()),
            "",
        )
        fake = fake or f"[REDACTED_{entity_type}]"
    except Exception:
        fake = f"[REDACTED_{entity_type}]"

    _fake_cache[original] = fake
    return fake


# ── Public API ────────────────────────────────────────────────────────────────

async def screen_text(text: str, session_id: str) -> Tuple[str, List[Dict]]:
    """
    Screen *text* for PII.  Returns (redacted_text, findings).

    Uses Presidio spans for precise replacement (end→start order so offsets
    stay valid), then Ollama for any contextual PII still in the redacted copy.
    All fakes stored in the session vault.
    """
    if not text or not text.strip():
        return text, []

    findings: List[Dict] = []
    already_replaced: set = set()

    # ── Pass 1: Presidio (span-based, most accurate) ─────────────────────────
    hits = _presidio_hits(text)
    chars = list(text)

    for hit in sorted(hits, key=lambda h: h["start"], reverse=True):
        original = hit["value"]
        if original in already_replaced:
            continue

        # Reuse existing fake for this session if we already vaulted it
        fake = vault.fake_for(session_id, original) or await _make_fake(
            hit["entity_type"], original
        )
        vault.put(session_id, fake, original)
        chars[hit["start"] : hit["end"]] = list(fake)
        already_replaced.add(original)
        findings.append({**hit, "fake": fake, "source": "presidio"})

    redacted = "".join(chars)

    # ── Pass 2: Ollama contextual ─────────────────────────────────────────────
    ollama_hits = await _ollama_hits(text)  # screen original to get clean spans

    for hit in ollama_hits:
        original = hit.get("value", "")
        if not original or original in already_replaced:
            continue
        if original not in redacted:
            continue

        fake = vault.fake_for(session_id, original) or await _make_fake(
            hit.get("type", "PII"), original
        )
        vault.put(session_id, fake, original)
        redacted = redacted.replace(original, fake)
        already_replaced.add(original)
        findings.append(
            {
                "entity_type": hit.get("type", "PII"),
                "value": original,
                "fake": fake,
                "source": "ollama",
                "score": 0.7,
            }
        )

    return redacted, findings
